slack :
  team : "your-team-name"
  channel : "#general"
  token : "your-slackbot-token"
gyazz : 
  - wiki  : test
  - wiki  : shokai
    user  : username
    pass  : password
ignore :
  - .書込認証
  - .完全認証
  - .passwd
